/**************************************************************************************************
* Name               : GEMS_BatchPromotionsUpdateHandler                                          *
* Description        : Implements logic for Promotions update                                     *
* Created Date       : 21/12/2017                                                                 *
* Created By         : Umair Khan (PWC Digital)                                                   *
* ----------------------------------------------------------------------------------------------- */

public class GEMS_BatchPromotionsUpdateHandler {
    
    private list<Academic_Year__c> lstAcademicYear;
    
    public GEMS_BatchPromotionsUpdateHandler(List<Academic_Year__c> p_lstAcademicYear){
    	lstAcademicYear = p_lstAcademicYear;
    }
    
    

}