public with sharing class GEMS_checkRecursiveTriggers {
    
    public static boolean runOnceForSR = true;
    
    public static boolean runOnceForAccount = true;
    
    public static boolean runOnceForLeadBI = true;
    public static boolean runOnceForLeadBU = true;
    public static boolean runOnceForLeadAI = true;
    public static boolean runOnceForLeadAU = true;
    public static boolean runOnceForLeadBD = true;
    
    
    public static boolean runOnceForEnquiryBI = true;
    public static boolean runOnceForEnquiryBU = true;
    public static boolean runOnceForEnquiryAI = true;
    public static boolean runOnceForEnquiryAU = true;
    public static boolean runOnceForEnquiryBD = true;
    
    public static boolean runOnceForEnrolledSR = false;
    
}