public with sharing class GEMS_PaymentReceiptBuilderCntlr {
	public string receiptID {get;set;}
    
    
    /*public void init(){
    	String receiptQueryStr ;
    	receiptQueryStr = GEMS_Utility.getAllField(Reviept__c.getSobjectType().getDescribe());
    	Reciept__c Receipt = Database.Query(receiptQueryStr); 
    	
    	HexaBPM__Service_Request__c SR = GEMS_Utility.getAllFields(HexaBPM__Service_Request__c.getSobjectType().getDescribe());
    }*/
}